// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtA1YTdgdf4X_jaroCj46VUp0D4rRlGyg',
    appId: '1:247305557002:web:dedf3ec12c6a3673abbbf3',
    messagingSenderId: '247305557002',
    projectId: 'smart-salon-v2',
    authDomain: 'smart-salon-v2.firebaseapp.com',
    storageBucket: 'smart-salon-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbgVJZ0XOwUhZPRAeCmbRk1SHu9V4NJXA',
    appId: '1:247305557002:android:540e68c7743411b9abbbf3',
    messagingSenderId: '247305557002',
    projectId: 'smart-salon-v2',
    storageBucket: 'smart-salon-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSlM2jrmtBuqaEJ4HTRQedVZ5LyD5Gv2Y',
    appId: '1:247305557002:ios:1a6994effed5ef1fabbbf3',
    messagingSenderId: '247305557002',
    projectId: 'smart-salon-v2',
    storageBucket: 'smart-salon-v2.firebasestorage.app',
    iosBundleId: 'com.example.smartSalonV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSlM2jrmtBuqaEJ4HTRQedVZ5LyD5Gv2Y',
    appId: '1:247305557002:ios:1a6994effed5ef1fabbbf3',
    messagingSenderId: '247305557002',
    projectId: 'smart-salon-v2',
    storageBucket: 'smart-salon-v2.firebasestorage.app',
    iosBundleId: 'com.example.smartSalonV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtA1YTdgdf4X_jaroCj46VUp0D4rRlGyg',
    appId: '1:247305557002:web:f333b94be25296fbabbbf3',
    messagingSenderId: '247305557002',
    projectId: 'smart-salon-v2',
    authDomain: 'smart-salon-v2.firebaseapp.com',
    storageBucket: 'smart-salon-v2.firebasestorage.app',
  );
}
